### ISSUE TITLE
Got Error when running docker-compose -f docker-compose-fluent-bit.yml up

### ISSUE THREAD

**Issue by wangran326990** [thakkaryash94/docker-grafana-loki-fluent-bit-sample#1]
fluent-bit    | Fluent Bit v1.4.6
fluent-bit    | * Copyright (C) 2019-2020 The Fluent Bit Authors
fluent-bit    | * Copyright (C) 2015-2018 Treasure Data
fluent-bit    | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
fluent-bit    | * https://fluentbit.io
fluent-bit    |
fluent-bit    | Output plugin 'loki' cannot be loaded
fluent-bit    | Error: You must specify an output target. Aborting
fluent-bit    |
fluent-bit exited with code 1

Thanks for your help

**Comment by thakkaryash94** [comment]
Hello, Thank you for the issue. There was a change in the plugin name that needs to be updated in `fluent-bit.conf` file. I have updated the code and tested it locally. Please try new code.

**Comment by wangran326990** [comment]
@thakkaryash94  Thanks for the update it works on my local.

**Comment by thakkaryash94** [comment]
You're welcome. I am closing the issue. Feel free to ask if any you need help 😄
